# Generated by Django 3.0.3 on 2020-05-20 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(default='Guest', max_length=20, unique=False, verbose_name='username'),
        ),
    ]
